// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajloaqewsqrwegjsgiar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqbG9hcWV3c3Fyd2VnanNnaWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTA5MjIsImV4cCI6MjA2ODgyNjkyMn0.8D8ZUpEiNdmOr5_7ND5IGgNWk0L6TFoP6zTQNYIwfRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});